INSERT INTO `competence` (`id`, `categorie`, `nom`, `reference`, `version`) VALUES
(1, '-Situation obligatoire', 'Participation à un projet d''évolution d''un SI (Solution applicative et d''infrastructure portant prioritairement sur le domaine de spécialité du candidat)', 'A', 0),
(2, '-Situation obligatoire', 'Prise en charge d''incidents et de demandes d''assistance liés au domaine de spécialité du candidat', 'B', 0),
(3, '-Situation obligatoire', 'Elaboration de documents relatifs à la production et à la fourniture de services', 'C', 0),
(4, '-Situation obligatoire', 'Productions relatives à la mise en place d''un dispositif de veille technologique et à l''étude d''une technologie, d''un composant, d''un outil ou d''une méthode', 'D', 0),
(9, 'D1.1 - Analyse de la demande', 'Analyse du cahier des charges d''un service à produire', 'A1.1.1', 0),
(10, 'D1.1 - Analyse de la demande', 'Étude de l''impact de l''intégration d''un service sur le système informatique', 'A1.1.2', 0),
(11, 'D1.1 - Analyse de la demande', 'Étude des exigences liées à la qualité attendue d''un service', 'A1.1.3', 0),
(12, 'D1.2 - Choix d''une solution', 'Élaboration et présentation d''un dossier de choix de solution technique', 'A1.2.1 ', 0),
(13, 'D1.2 - Choix d''une solution', 'Rédaction des spécifications techniques de la solution retenue', 'A1.2.2', 0),
(14, 'D1.2 - Choix d''une solution', 'Évaluation des risques liés à l''utilisation d''un service ', 'A1.2.3', 0),
(15, 'D1.2 - Choix d''une solution', 'Détermination des tests nécessaires à la validation d''un service', 'A1.2.4', 0),
(16, 'D1.2 - Choix d''une solution', 'Définition des niveaux d''habilitation associés à un service ', 'A1.2.5', 0),
(17, 'D1.3 - Mise en production d’un service', 'Test d''intégration et d''acceptation d''un service ', 'A1.3.1 ', 0),
(18, 'D1.3 - Mise en production d’un service', 'Définition des éléments nécessaires à la continuité d''un service ', 'A1.3.2', 0),
(19, 'D1.3 - Mise en production d’un service', 'Accompagnement de la mise en place d''un nouveau service ', 'A1.3.3', 0),
(20, 'D1.3 - Mise en production d’un service', 'Déploiement d''un service ', 'A1.3.4', 0),
(21, 'D1.4 - Travail en mode projet', 'Participation à un projet ', 'A1.4.1 ', 0),
(22, 'D1.4 - Travail en mode projet', 'Évaluation des indicateurs de suivi d''un projet et justification des écarts ', 'A1.4.2', 0),
(23, 'D1.4 - Travail en mode projet', 'Gestion des ressources ', 'A1.4.3', 0),
(24, 'D2.1 - Exploitation des services', 'Accompagnement des utilisateurs dans la prise en main d''un service ', 'A2.1.1', 0),
(25, 'D2.1 - Exploitation des services', 'Évaluation et maintien de la qualité d''un service ', 'A2.1.2', 0),
(26, 'D2.2 - Gestion des incidents et des demandes d’assistance', 'Suivi et résolution d''incidents ', 'A2.2.1', 0),
(27, 'D2.2 - Gestion des incidents et des demandes d’assistance', 'Suivi et réponse à des demandes d''assistance ', 'A2.2.2', 0),
(28, 'D2.2 - Gestion des incidents et des demandes d’assistance', 'Réponse à une interruption de service ', 'A2.2.3', 0),
(29, 'D2.3 - Gestion des problèmes et des changements', 'Identification, qualification et évaluation d''un problème ', 'A2.3.1', 0),
(30, 'D2.3 - Gestion des problèmes et des changements', 'Proposition d''amélioration d''un service ', 'A2.3.2', 0),
(31, 'D3.2 - Installation d’une solution d’infrastructure', 'Installation et configuration d''éléments d''infrastructure ', 'A3.2.1', 0),
(32, 'D3.2 - Installation d’une solution d’infrastructure', 'Remplacement ou mise à jour d''éléments défectueux ou obsolètes', 'A3.2.2', 0),
(33, 'D4.1 - Conception et réalisation d’une solution applicative', 'Proposition d''une solution applicative ', 'A4.1.1', 0),
(34, 'D4.1 - Conception et réalisation d’une solution applicative', 'Conception ou adaptation de l''interface utilisateur d''une solution applicative ', 'A4.1.2', 0),
(35, 'D4.1 - Conception et réalisation d’une solution applicative', 'Conception ou adaptation d''une base de données ', 'A4.1.3', 0),
(36, 'D4.1 - Conception et réalisation d’une solution applicative', 'Définition des caractéristiques d''une solution applicative ', 'A4.1.4', 0),
(37, 'D4.1 - Conception et réalisation d’une solution applicative', 'Prototypage de composants logiciels ', 'A4.1.5', 0),
(38, 'D4.1 - Conception et réalisation d’une solution applicative', 'Gestion d''environnements de développement et de test', 'A4.1.6', 0),
(39, 'D4.1 - Conception et réalisation d’une solution applicative', 'Développement, utilisation ou adaptation de composants logiciels', 'A4.1.7', 0),
(40, 'D4.1 - Conception et réalisation d’une solution applicative', 'Réalisation des tests nécessaires à la validation d''éléments adaptés ou développés', 'A4.1.8', 0),
(41, 'D4.1 - Conception et réalisation d’une solution applicative', 'Rédaction d''une documentation technique', 'A4.1.9', 0),
(42, 'D4.1 - Conception et réalisation d’une solution applicative', 'Rédaction d''une documentation d''utilisation ', 'A4.1.10', 0),
(43, 'D4.2 - Maintenance d''une solution applicative', 'Analyse et correction d''un dysfonctionnement, d''un problème de qualité de service ou de sécurité', 'A4.2.1', 0),
(44, 'D4.2 - Maintenance d''une solution applicative', 'Adaptation d''une solution applicative aux évolutions de ses composants', 'A4.2.2', 0),
(45, 'D4.2 - Maintenance d''une solution applicative', 'Réalisation des tests nécessaires à la mise en production d''éléments mis à jour', 'A4.2.3', 0),
(46, 'D4.2 - Maintenance d''une solution applicative', 'Mise à jour d''une documentation technique', 'A4.2.4', 0),
(47, 'D5.1 - Gestion des configurations', 'Mise en place d''une gestion de configuration', 'A5.1.1', 0),
(48, 'D5.1 - Gestion des configurations', 'Recueil d''informations sur une configuration et ses éléments', 'A5.1.2', 0),
(49, 'D5.1 - Gestion des configurations', 'Suivi d''une configuration et de ses éléments', 'A5.1.3', 0),
(50, 'D5.1 - Gestion des configurations', 'Étude de propositions de contrat de service (client, fournisseur)', 'A5.1.4', 0),
(51, 'D5.1 - Gestion des configurations', 'Évaluation d''un élément de configuration ou d''une configuration', 'A5.1.5', 0),
(52, 'D5.1 - Gestion des configurations', 'Évaluation d''un investissement informatique', 'A5.1.6', 0),
(53, 'D5.2 - Gestion des compétences', 'Exploitation des référentiels, normes et standards adoptés par le prestataire', 'A5.2.1', 0),
(54, 'D5.2 - Gestion des compétences', 'Veille technologique', 'A5.2.2', 0),
(55, 'D5.2 - Gestion des compétences', 'Repérage des compléments de formation ou d''auto-formation', 'A5.2.3', 0),
(56, 'D5.2 - Gestion des compétences', ' Étude d''une technologie, d''un composant, d''un outil ou d''une méthode', 'A5.2.4', 0);