// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fr.edu.eportfolio.domain;

import fr.edu.eportfolio.domain.Activite;
import fr.edu.eportfolio.domain.ActiviteDataOnDemand;
import fr.edu.eportfolio.domain.ActiviteIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ActiviteIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ActiviteIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ActiviteIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ActiviteIntegrationTest: @Transactional;
    
    @Autowired
    private ActiviteDataOnDemand ActiviteIntegrationTest.dod;
    
    @Test
    public void ActiviteIntegrationTest.testCountActivites() {
        Assert.assertNotNull("Data on demand for 'Activite' failed to initialize correctly", dod.getRandomActivite());
        long count = Activite.countActivites();
        Assert.assertTrue("Counter for 'Activite' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ActiviteIntegrationTest.testFindActivite() {
        Activite obj = dod.getRandomActivite();
        Assert.assertNotNull("Data on demand for 'Activite' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Activite' failed to provide an identifier", id);
        obj = Activite.findActivite(id);
        Assert.assertNotNull("Find method for 'Activite' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Activite' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ActiviteIntegrationTest.testFindAllActivites() {
        Assert.assertNotNull("Data on demand for 'Activite' failed to initialize correctly", dod.getRandomActivite());
        long count = Activite.countActivites();
        Assert.assertTrue("Too expensive to perform a find all test for 'Activite', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Activite> result = Activite.findAllActivites();
        Assert.assertNotNull("Find all method for 'Activite' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Activite' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ActiviteIntegrationTest.testFindActiviteEntries() {
        Assert.assertNotNull("Data on demand for 'Activite' failed to initialize correctly", dod.getRandomActivite());
        long count = Activite.countActivites();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Activite> result = Activite.findActiviteEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Activite' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Activite' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ActiviteIntegrationTest.testFlush() {
        Activite obj = dod.getRandomActivite();
        Assert.assertNotNull("Data on demand for 'Activite' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Activite' failed to provide an identifier", id);
        obj = Activite.findActivite(id);
        Assert.assertNotNull("Find method for 'Activite' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyActivite(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Activite' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ActiviteIntegrationTest.testMergeUpdate() {
        Activite obj = dod.getRandomActivite();
        Assert.assertNotNull("Data on demand for 'Activite' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Activite' failed to provide an identifier", id);
        obj = Activite.findActivite(id);
        boolean modified =  dod.modifyActivite(obj);
        Integer currentVersion = obj.getVersion();
        Activite merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Activite' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ActiviteIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Activite' failed to initialize correctly", dod.getRandomActivite());
        Activite obj = dod.getNewTransientActivite(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Activite' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Activite' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Activite' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ActiviteIntegrationTest.testRemove() {
        Activite obj = dod.getRandomActivite();
        Assert.assertNotNull("Data on demand for 'Activite' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Activite' failed to provide an identifier", id);
        obj = Activite.findActivite(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Activite' with identifier '" + id + "'", Activite.findActivite(id));
    }
    
}
