// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fr.edu.eportfolio.domain;

import fr.edu.eportfolio.domain.Competence;
import fr.edu.eportfolio.domain.CompetenceDataOnDemand;
import fr.edu.eportfolio.domain.CompetenceIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CompetenceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CompetenceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CompetenceIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CompetenceIntegrationTest: @Transactional;
    
    @Autowired
    private CompetenceDataOnDemand CompetenceIntegrationTest.dod;
    
    @Test
    public void CompetenceIntegrationTest.testCountCompetences() {
        Assert.assertNotNull("Data on demand for 'Competence' failed to initialize correctly", dod.getRandomCompetence());
        long count = Competence.countCompetences();
        Assert.assertTrue("Counter for 'Competence' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CompetenceIntegrationTest.testFindCompetence() {
        Competence obj = dod.getRandomCompetence();
        Assert.assertNotNull("Data on demand for 'Competence' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Competence' failed to provide an identifier", id);
        obj = Competence.findCompetence(id);
        Assert.assertNotNull("Find method for 'Competence' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Competence' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CompetenceIntegrationTest.testFindAllCompetences() {
        Assert.assertNotNull("Data on demand for 'Competence' failed to initialize correctly", dod.getRandomCompetence());
        long count = Competence.countCompetences();
        Assert.assertTrue("Too expensive to perform a find all test for 'Competence', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Competence> result = Competence.findAllCompetences();
        Assert.assertNotNull("Find all method for 'Competence' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Competence' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CompetenceIntegrationTest.testFindCompetenceEntries() {
        Assert.assertNotNull("Data on demand for 'Competence' failed to initialize correctly", dod.getRandomCompetence());
        long count = Competence.countCompetences();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Competence> result = Competence.findCompetenceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Competence' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Competence' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CompetenceIntegrationTest.testFlush() {
        Competence obj = dod.getRandomCompetence();
        Assert.assertNotNull("Data on demand for 'Competence' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Competence' failed to provide an identifier", id);
        obj = Competence.findCompetence(id);
        Assert.assertNotNull("Find method for 'Competence' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCompetence(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Competence' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CompetenceIntegrationTest.testMergeUpdate() {
        Competence obj = dod.getRandomCompetence();
        Assert.assertNotNull("Data on demand for 'Competence' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Competence' failed to provide an identifier", id);
        obj = Competence.findCompetence(id);
        boolean modified =  dod.modifyCompetence(obj);
        Integer currentVersion = obj.getVersion();
        Competence merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Competence' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CompetenceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Competence' failed to initialize correctly", dod.getRandomCompetence());
        Competence obj = dod.getNewTransientCompetence(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Competence' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Competence' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Competence' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CompetenceIntegrationTest.testRemove() {
        Competence obj = dod.getRandomCompetence();
        Assert.assertNotNull("Data on demand for 'Competence' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Competence' failed to provide an identifier", id);
        obj = Competence.findCompetence(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Competence' with identifier '" + id + "'", Competence.findCompetence(id));
    }
    
}
