// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fr.edu.eportfolio.domain;

import fr.edu.eportfolio.domain.SituationPro;
import fr.edu.eportfolio.domain.SituationProDataOnDemand;
import fr.edu.eportfolio.domain.SituationProIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SituationProIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SituationProIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SituationProIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SituationProIntegrationTest: @Transactional;
    
    @Autowired
    private SituationProDataOnDemand SituationProIntegrationTest.dod;
    
    @Test
    public void SituationProIntegrationTest.testCountSituationProes() {
        Assert.assertNotNull("Data on demand for 'SituationPro' failed to initialize correctly", dod.getRandomSituationPro());
        long count = SituationPro.countSituationProes();
        Assert.assertTrue("Counter for 'SituationPro' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SituationProIntegrationTest.testFindSituationPro() {
        SituationPro obj = dod.getRandomSituationPro();
        Assert.assertNotNull("Data on demand for 'SituationPro' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SituationPro' failed to provide an identifier", id);
        obj = SituationPro.findSituationPro(id);
        Assert.assertNotNull("Find method for 'SituationPro' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SituationPro' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SituationProIntegrationTest.testFindAllSituationProes() {
        Assert.assertNotNull("Data on demand for 'SituationPro' failed to initialize correctly", dod.getRandomSituationPro());
        long count = SituationPro.countSituationProes();
        Assert.assertTrue("Too expensive to perform a find all test for 'SituationPro', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SituationPro> result = SituationPro.findAllSituationProes();
        Assert.assertNotNull("Find all method for 'SituationPro' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SituationPro' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SituationProIntegrationTest.testFindSituationProEntries() {
        Assert.assertNotNull("Data on demand for 'SituationPro' failed to initialize correctly", dod.getRandomSituationPro());
        long count = SituationPro.countSituationProes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SituationPro> result = SituationPro.findSituationProEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SituationPro' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SituationPro' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SituationProIntegrationTest.testFlush() {
        SituationPro obj = dod.getRandomSituationPro();
        Assert.assertNotNull("Data on demand for 'SituationPro' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SituationPro' failed to provide an identifier", id);
        obj = SituationPro.findSituationPro(id);
        Assert.assertNotNull("Find method for 'SituationPro' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySituationPro(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SituationPro' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SituationProIntegrationTest.testMergeUpdate() {
        SituationPro obj = dod.getRandomSituationPro();
        Assert.assertNotNull("Data on demand for 'SituationPro' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SituationPro' failed to provide an identifier", id);
        obj = SituationPro.findSituationPro(id);
        boolean modified =  dod.modifySituationPro(obj);
        Integer currentVersion = obj.getVersion();
        SituationPro merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SituationPro' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SituationProIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SituationPro' failed to initialize correctly", dod.getRandomSituationPro());
        SituationPro obj = dod.getNewTransientSituationPro(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SituationPro' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SituationPro' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'SituationPro' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SituationProIntegrationTest.testRemove() {
        SituationPro obj = dod.getRandomSituationPro();
        Assert.assertNotNull("Data on demand for 'SituationPro' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SituationPro' failed to provide an identifier", id);
        obj = SituationPro.findSituationPro(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SituationPro' with identifier '" + id + "'", SituationPro.findSituationPro(id));
    }
    
}
