// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fr.edu.eportfolio.domain;

import fr.edu.eportfolio.domain.SituationProIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SituationProIntegrationTest_Roo_Configurable {
    
    declare @type: SituationProIntegrationTest: @Configurable;
    
}
